# Generated by Django 5.2.4 on 2025-07-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDataApiLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logger_session_id', models.CharField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('level', models.CharField(blank=True, null=True)),
                ('logger_name', models.CharField(blank=True, null=True)),
                ('message', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'business_data_api_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=250)),
                ('legal_form', models.CharField(max_length=100)),
                ('krs_number', models.CharField(max_length=14)),
                ('nip_number', models.CharField(max_length=10)),
                ('regon_number', models.CharField(max_length=14)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('voivodeship', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_number', models.CharField(blank=True, max_length=6, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('webpage', models.CharField(blank=True, max_length=2083, null=True)),
            ],
            options={
                'db_table': 'company_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyInfoDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(blank=True, null=True)),
                ('record_created_at', models.DateTimeField(blank=True, null=True)),
                ('registered_at_krs_system_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_info_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KrsDfDocuments',
            fields=[
                ('hash_id', models.CharField(primary_key=True, serialize=False)),
                ('krs_number', models.CharField(blank=True, null=True)),
                ('document_internal_id', models.CharField(blank=True, null=True)),
                ('document_type', models.CharField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, null=True)),
                ('document_date_from', models.CharField(blank=True, null=True)),
                ('document_date_to', models.CharField(blank=True, null=True)),
                ('document_status', models.CharField(blank=True, null=True)),
                ('document_content_save_name', models.CharField(blank=True, null=True)),
                ('document_content_file_extension', models.CharField(blank=True, null=True)),
                ('document_content', models.BinaryField(blank=True, null=True)),
                ('record_created_at', models.DateTimeField(blank=True, null=True)),
                ('record_updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'krs_df_documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RawKrsApiFullExtract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_current', models.BooleanField(blank=True, null=True)),
                ('krs_number', models.CharField(max_length=10)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'db_table': 'raw_krs_api_full_extract',
                'managed': False,
            },
        ),
    ]
